# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ursName', models.CharField(default='Name', max_length=50)),
                ('ursPassword', models.CharField(default='******', max_length=50)),
                ('Dscrb', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w3kun.Article')),
                ('friends', models.ManyToManyField(related_name='_author_friends_+', to='w3kun.Author')),
            ],
        ),
    ]
