# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w3kun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_author_friends_+', to='w3kun.Author'),
        ),
    ]
