# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w3kun', '0005_auto_20171126_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='launchtime',
            field=models.DateTimeField(auto_now=True, verbose_name='发布日期'),
        ),
    ]
